#!/bin/bash
INSTALL_PREFIX=/users/profs/2017/francois.trahay/soft/install

# HWLOC stuff
HWLOC_ROOT=$INSTALL_PREFIX/hwloc
PATH=$PATH:$HWLOC_ROOT/bin/
MANPATH=$MANPATH:$HWLOC_ROOT/share/man
LD_LIBRARY_PATH=$HWLOC_ROOT/lib:$LD_LIBRARY_PATH
PKG_CONFIG_PATH=$HWLOC_ROOT/lib/pkgconfig:$PKG_CONFIG_PATH

# CUDA stuff
CUDA_ROOT=/usr/local/cuda
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CUDA_ROOT}/lib/
PATH=$PATH:${CUDA_ROOT}/bin/:${CUDA_ROOT}/open64/bin/

# MPI stuff
MPI_ROOT=$INSTALL_PREFIX/openmpi/
PATH=${MPI_ROOT}/bin:$PATH
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${MPI_ROOT}/lib
MANPATH=$MANPATH:$MPI_ROOT/share/man

# EZTrace
EZTRACE_ROOT=$INSTALL_PREFIX/eztrace/
PATH=$PATH:$EZTRACE_ROOT/bin

# ViTE
VITE_ROOT=$INSTALL_PREFIX/vite
export PATH=$PATH:$VITE_ROOT/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$VITE_ROOT/lib
export QT_QPA_PLATFORM_PLUGIN_PATH=$VITE_ROOT/plugins

export LD_LIBRARY_PATH
export PATH
export MANPATH
export PKG_CONFIG_PATH
